### ISSUE TITLE
website not working

### ISSUE THREAD

**Issue by aimageofthearchiveorgmusicaudio** [lanye74/lanye74.github.io#1]
![image](https://user-images.githubusercontent.com/86971741/228059563-a4e80e33-0053-4a03-9e61-b966ef61c16d.png)

**Comment by lanye74** [comment]
i forgor to rename the repository when i changed my name

**Comment by aimageofthearchiveorgmusicaudio** [comment]
btw when is the site done

**Comment by lanye74** [comment]
i dunno. i haven't actively worked on it in months, i'm expending my energies elsewhere

whenever i actually need this website to be functional (i.e. whenever i turn this into a portfolio) i'll probably completely redo the homepage and delete all the projects, moving whatever i want to keep (like shady) into separate repos
